# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\swedigarch\swedigarch_plugin\select_subclasses_to_filter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectSubClassesToFilterDialog(object):
    def setupUi(self, SelectSubClassesToFilterDialog):
        SelectSubClassesToFilterDialog.setObjectName("SelectSubClassesToFilterDialog")
        SelectSubClassesToFilterDialog.resize(550, 630)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Projects\\swedigarch\\swedigarch_plugin\\../Projects/swedigarch/swedigarch_plugin/assets/svedigark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectSubClassesToFilterDialog.setWindowIcon(icon)
        SelectSubClassesToFilterDialog.setSizeGripEnabled(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(SelectSubClassesToFilterDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(SelectSubClassesToFilterDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(False)
        self.splitter.setHandleWidth(10)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_top = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_top.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_top.setObjectName("verticalLayout_top")
        self.groupBoxSubClasses = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBoxSubClasses.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBoxSubClasses.setObjectName("groupBoxSubClasses")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxSubClasses)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tree_widget_class_subclass = QtWidgets.QTreeWidget(self.groupBoxSubClasses)
        self.tree_widget_class_subclass.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tree_widget_class_subclass.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tree_widget_class_subclass.setObjectName("tree_widget_class_subclass")
        self.tree_widget_class_subclass.headerItem().setText(0, "1")
        self.tree_widget_class_subclass.header().setVisible(False)
        self.tree_widget_class_subclass.header().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tree_widget_class_subclass, 0, 0, 1, 1)
        self.verticalLayout_top.addWidget(self.groupBoxSubClasses)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_bottom = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_bottom.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_bottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_bottom.setObjectName("verticalLayout_bottom")
        self.groupBoxSelected = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBoxSelected.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBoxSelected.setObjectName("groupBoxSelected")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxSelected)
        self.gridLayout.setObjectName("gridLayout")
        self.lwSelectedSubClasses = QtWidgets.QListWidget(self.groupBoxSelected)
        self.lwSelectedSubClasses.setObjectName("lwSelectedSubClasses")
        self.gridLayout.addWidget(self.lwSelectedSubClasses, 0, 0, 1, 1)
        self.verticalLayout_bottom.addWidget(self.groupBoxSelected)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_filter_info = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_filter_info.setObjectName("lbl_filter_info")
        self.horizontalLayout.addWidget(self.lbl_filter_info)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_box = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_2)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout.addWidget(self.button_box)
        self.verticalLayout_bottom.addLayout(self.horizontalLayout)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(SelectSubClassesToFilterDialog)
        self.button_box.accepted.connect(SelectSubClassesToFilterDialog.accept) # type: ignore
        self.button_box.rejected.connect(SelectSubClassesToFilterDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectSubClassesToFilterDialog)

    def retranslateUi(self, SelectSubClassesToFilterDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectSubClassesToFilterDialog.setWindowTitle(_translate("SelectSubClassesToFilterDialog", "Select Subclasses to filter"))
        self.groupBoxSubClasses.setTitle(_translate("SelectSubClassesToFilterDialog", "All Classes/SubClasses with objects inte the selected databases"))
        self.groupBoxSelected.setTitle(_translate("SelectSubClassesToFilterDialog", "Selected Subclasses for filtering"))
        self.lbl_filter_info.setText(_translate("SelectSubClassesToFilterDialog", "TextLabel"))
